- name: Deploy app using Docker
  hosts: webservers
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Stop existing container
      shell: docker rm -f myapp || true

    - name: Pull latest image
      shell: docker pull yourdockerhubuser/myapp:latest

    - name: Run container
      shell: docker run -d -p 80:3000 --name myapp yourdockerhubuser/myapp:latest
